#PostgreSQL configuration

spring.datasource.url =jdbc:postgresql://dpg-d5sovukr85hc73do7rcg-a.singapore-postgres.render.com/moneymanager_wszx
spring.datasource.username=moneymanager_wszx_user
spring.datasource.password=VrUQam9NdEItO4FxlCFQAwuO88ofee50